// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'iconActivation': string;
  'iconActivationActive': string;
  'iconHome': string;
  'iconHomeActive': string;
  'iconMeasurement': string;
  'iconMeasurementActive': string;
  'iconPlanning': string;
  'iconPlanningActive': string;
  'iconSettings': string;
  'iconSettingsActive': string;
  'iconn': string;
  'logo': string;
  'planningSubMenu': string;
  'subNavList': string;
}
export const cssExports: CssExports;
export default cssExports;
