// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'slide1': string;
  'slide2': string;
  'slide3': string;
}
export const cssExports: CssExports;
export default cssExports;
